sources:
transforms:
  - namingConvention:
      mode: bare | wrap
      typeNames: pascalCase
      enumValues: upperCase
      fieldNames: camelCase
      fieldArgumentNames: camelCase
additionalTypeDefs: |
  """
  Describes the authentication object as provided by Auth0.
  """
  type AuthenticationInfo {
    """
    String that uniquely identifies an authenticated user.
    """
    sub: String!
  }

  extend type Query {
    """
    The authentication information of the request.
    """
    authInfo: AuthenticationInfo
  }
