sources:
  - null
plugins:
  - auth0: null
  - deduplicateRequest: {}
  - maxDepth: null
  - maxTokens: null
  - rateLimit:
      config: []
transforms:
  - namingConvention:
      mode: bare | wrap
      typeNames: pascalCase
      enumValues: upperCase
      fieldNames: camelCase
      fieldArgumentNames: camelCase
