name: Build Mesh

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Assemble the schema
        run: node assemble.js
      - name: Build the mesh
        run: npm run build
      - name: Save the schema as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: supergraph-schema
          path: |
            ./mesh/schema.graphql