name: Build Mesh

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Assemble the schema
        run: node assemble.js
      - name: Build the mesh
        run: npm run build
      - name: Save the schema to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Succeful Mesh Build!'